### ISSUE TITLE
v.1.0.0 Development 

### ISSUE THREAD

**Issue by turtlepod** [Astoundify/briteverify-for-wp#2]
Last night, I created the settings in "Settings > BriteVerify" for the API Key.
Currently working on GF using GF Add-ons Framework.

**Comment by turtlepod** [comment]
Just update the plugin:
1. Add readme.txt
2. Remove API Key validation
3. Only load GF Script if it's enabled in a field.
3. Fix plugins loaded. Sometimes it's not loaded properly.

Here's the screenshot for the readme/wp org:
https://dl.dropboxusercontent.com/u/32880842/etc7/briteverify-assets/new/screenshot-1.png
https://dl.dropboxusercontent.com/u/32880842/etc7/briteverify-assets/new/screenshot-2.png
https://dl.dropboxusercontent.com/u/32880842/etc7/briteverify-assets/new/screenshot-3.png

**Comment by adampickering** [comment]
Thanks!!!
