### ISSUE TITLE
Remove BriteVerify AJAX Checking

### ISSUE THREAD

**Issue by turtlepod** [Astoundify/briteverify-for-wp#7]
I don't think it's necessary to check email via BriteVerify using AJAX on input change.
There are occasion when their server timeout and return error on the validation.

Or, we can remove the server error response from the AJAX checking. So, on AJAX checking it will only return error if their server explicitly return invalid (or disposable).

GravityForms and EDD both have validation filter on submit (before processing the data).

Note: On submit, it will still check the data to BV, so for every submission there will be minimum 2 check to BV.

What do you think @spencerfinnell & @adampickering ? Do we need to remove the AJAX checking or simply remove the error from AJAX checking?

**Comment by spencerfinnell** [comment]
I actually thought it was a little weird it was doing it on keypress. I would prefer to see filtered validation on EDD and GravityForms that return that error along with other relevant errors.

**Comment by turtlepod** [comment]
It actually do validation on submit too (along with other relevant errors).

The idea of using ajax is from @adampickering https://github.com/Astoundify/briteverify-for-wp/issues/1
And I think that it's an interesting idea to implement.

But the implementation (the code is overly complex in GF) and user experience (at least when i test it) not very good.

**Comment by turtlepod** [comment]
@adampickering let me know if you want to remove this feature. It's relatively easy to remove.

**Comment by adampickering** [comment]
Yeah can you please go ahead and remove
