### ISSUE TITLE
Unknown Email As Valid ?

### ISSUE THREAD

**Issue by turtlepod** [Astoundify/briteverify-for-wp#8]
In briteverify gravityforms @volodymyrpekh submitted an issue:
https://github.com/Astoundify/briteverify-gravityforms/issues/4

Apparently some domain (which is valid) return as "unknown" or even "accept-all" response.
The idea is to loosen up validation method.

**Previously:** 

Only allow email with return value "valid", other than that, reject.

**Suggestion:**

Only reject if the return value is explicit "invalid" other than that, accept.

What do you think about this? Do we need settings for this? 
@spencerfinnell @adampickering

**Comment by adampickering** [comment]
I think a setting will be good enough, option to accept all incoming emails
apart from reject

**Comment by turtlepod** [comment]
cc @volodymyrpekh

I just added the option to select validation method in dev branch.
If you have time please download this https://github.com/Astoundify/briteverify-for-wp/archive/david.zip
And test the option/settings.

**Comment by volodymyrpekh** [comment]
@turtlepod Thank for such a quick turnaround!

"accept-all" works like magic. 
"unknown" returns "Unable to validate email. Email validation request error. Please try again or contact administrator."

**Comment by turtlepod** [comment]
@volodymyrpekh thank you for the test. I really appreciate it.

I just fixed the issue. please re-download and check the latest from dev branch to test this:
https://github.com/Astoundify/briteverify-for-wp/archive/david.zip

**Comment by volodymyrpekh** [comment]
@turtlepod Works great now. Thanks for an update.

Could be a good idea to add a third option to validation method:
- Green (only reject if email is invalid)
- Yellow (only reject if email is invalid and/or unknown)
- Red (only allow if email is valid)

**Comment by turtlepod** [comment]
interesting.

From "green", "yellow", "red" which one you will actually use?

(note: I'm already AFK, will reply further tomorrow)


On Feb 16, 2017 1:39 AM, "Vlad Pekh" <notifications@github.com> wrote:

@turtlepod <https://github.com/turtlepod> Works great now. Thanks for an
update.

Could be a good idea to add a third option to validation method:

   - Green (only reject if email is invalid)
   - Yellow (only reject if email is invalid and/or unknown)
   - Red (only allow if email is valid)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Astoundify/briteverify-for-wp/issues/8#issuecomment-280099103>,
or mute the thread

**Comment by volodymyrpekh** [comment]
@turtlepod Depends on project. From my point of view **Green** and **Yellow** would be my favourite options. 

> interesting.
> 
> From "green", "yellow", "red" which one you will actually use?
> 
> (note: I'm already AFK, will reply further tomorrow)

**Comment by turtlepod** [comment]
In my opinion it's not necessary.
The idea of using BV is to prevent spam.

A perfect spam filter would be remove spam with 100% accuracy.
A good one probably still have couple of spam in.
A bad one would be detecting a real person as spam.

I think the risk/cost of not allowing a real person to contact (e.g potential client) outweigh the benefit of getting 1 more spam in.

I even think that having the option to set to strict is not really needed (but still useful for testing/debug purposes).

What do you think @spencerfinnell @adampickering

**Comment by adampickering** [comment]
Sounds like feature creep!
